### ISSUE TITLE
Setup_Cuda.py error during installation 

### ISSUE THREAD

**Issue by alwansm** [MrGF/py-faster-rcnn-windows#24]
i am getting the following error:

> D:\py-faster-rcnn\lib>python setup_cuda.py install

`running install
running bdist_egg
running egg_info
writing py_fast_rcnn_gpu.egg-info\PKG-INFO
writing dependency_links to py_fast_rcnn_gpu.egg-info\dependency_links.txt
writing top-level names to py_fast_rcnn_gpu.egg-info\top_level.txt
writing manifest file 'py_fast_rcnn_gpu.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
building 'nms.gpu_nms' extension
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\nvcc.exe --compiler-bindir "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin" -c "-IC:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\site-packages\numpy\core\include" "-IC:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\include" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.16299.0\cppwinrt" nms\gpu_nms.cu -o build\temp.win-amd64-3.6\Release\nms\gpu_nms.obj -O --ptxas-options=-v -arch=sm_35 -c --compiler-options=/nologo,/Ox,/W3,/GL,/DNDEBUG,/MD
gpu_nms.cu
C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/include\yvals.h(172): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.12.
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v9.0\\bin\\nvcc.exe' failed with exit status 2`

More information:
Windows 10
CUDA 9.0
VS 2017
GTX 1080
Python 3.6

**Comment by ycui123** [comment]
Hi @alwansm, 

Did you solve the problem? I'm running into the same problem.

**Comment by thijsgelton** [comment]
Bump, any solution to this problem?

**Comment by tomjeans** [comment]
compiling the code in vs2015 using  MSVC 14.0 can work on cuda 9.0

**Comment by vanish012** [comment]
我是py3.5和py2.7共存的，切换到py2.7下运行 python setup_cuda.py install，报错Python error: Microsoft Visual C++ 9.0 is required，之后运行SET VS90COMNTOOLS=%VS140COMNTOOLS%，因为我的是vs2015，之后再次运行python setup_cuda.py install就编译成功了
